[package]

name = "capnp"
version = "0.11.2"
authors = [ "David Renshaw <dwrenshaw@gmail.com>" ]
license = "MIT"
description = "runtime library for Cap'n Proto data encoding"
repository = "https://github.com/capnproto/capnproto-rust"
documentation = "https://docs.capnproto-rust.org/capnp/"
edition = "2018"

readme = "README.md"

keywords = ["encoding", "protocol", "serialization"]

[lib]

name = "capnp"
path = "src/lib.rs"

[dependencies]
quickcheck = { version = "0.9", optional = true }

[dev-dependencies]
quickcheck = "0.9"

[features]
default = ["unaligned"]
rpc_try = []
unaligned = []

