[package]

name = "calculator"
version = "0.0.0"
authors = [ "David Renshaw <dwrenshaw@sandstorm.io>"  ]
build = "build.rs"
edition = "2018"

[[bin]]

name = "calculator"
path = "main.rs"

[build-dependencies]
capnpc = { path = "../../../capnpc" }

[dependencies]
capnp = { path = "../../../capnp" }
futures = "0.3.0"
async-std = { git = "https://github.com/async-rs/async-std"}

[dependencies.capnp-rpc]
path = "../.."
